name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build
        with:
          node-version: 16.x
          cache: 'npm'
          registry-url: https://npm.pkg.github.com/
      - run: mbt build
