name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: help
        uses: SAP/project-piper-action@master
        with:
          command: help
      - name: Build
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
      - name: cTMSupload
        uses: SAP/project-piper-action@master
        with:
          command: tmsUpload
